# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "Aya-Mohamed945"
    open-pull-requests-limit: 5
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "Aya-Mohamed945"
    open-pull-requests-limit: 5
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "Aya-Mohamed945"

  - package-ecosystem: "docker"
    directory: "/backend/docker"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"